# Generated by Django 2.2.28 on 2023-07-07 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cvvrt'),
    ]

    operations = [
        migrations.AddField(
            model_name='fnvn',
            name='rel_cvvrt_1_1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fnvn_rel_cvvrt_1_1', to='home.Cvvrt'),
        ),
    ]
