# Generated by Django 2.2.28 on 2023-07-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_fvdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='fvdf',
            name='addf',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
