# Generated by Django 2.2.28 on 2023-07-07 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20230707_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='fnvn',
            name='rel_fvdf_1_1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fnvn_rel_fvdf_1_1', to='home.Fvdf'),
        ),
    ]
